
function v_widget_lang() {
	this.locale_dict = {
		en: {
			new: "New",
			more: "More",
			less: "Less",
			product_page: "Product Page",
			landing_page: "Landing Page",
			view_product_page: "View product page",
			view_product_citations: "View product citations",
			article_share: "Share Article",
			author_locations: "Author Locations",
			read_article: "Read Article",
			show: "Results per page",
			search: "Search",
			search_all_publications: "Search all publications",
			publication_filters: "Publication filters",
			citation: "Citation",
			citations: "Citations",
			product_citations: "Product Citations",
			scientific_citations: "Scientific Citations",
			citation_count: "Citation Count",
			image: "Image",
			images: "Images",
			product_images: "Product Images",
			video: "Video",
			videos: "Videos",
			table: "Table",
			tables: "Tables",
			magnify_image: "Magnify image",
			trend: "Trend",
			sort_by: "Sort by",
			date: "Date",
			export: "Export",
			export_page_citations: "Export this page of citations",
			export_100_citations: "Export first 100 citations",
			page_citations: "Page of citations",
			first_100_citations: "First 100 citations",
			article_snippet: "Article Snippet",
			figure: "Figure",
			figure_legend: "Figure Legend",
			table_legend: "Table Legend",
			video_legend: "Video Legend",
			bioz_stars_product_rating: "Bioz Stars Product Ratings",
			bioz_stars_description: "The world&#39;s only objective ratings for scientific research products",
			learn_more: "Learn more",
			name: "Name",
			email: "Email",
			share_this_article: "Share this article",
			share_this_instructions: "Please enter the name and email of the person you wish to share this article with",
			share_this_patent: "Share this patent",
			share_this_patent_instructions: "Please enter the name and email of the person you wish to share this patent with",
			share_this_supplemental: "Share this document",
			share_this_supplemental_instructions: "Please enter the name and email of the person you wish to share this document with",
			share_this_clinical_trial: "Share this document",
			share_this_clinical_trial_instructions: "Please enter the name and email of the person you wish to share this document with",
			share_this_phd_thesis: "Share this document",
			share_this_phd_thesis_instructions: "Please enter the name and email of the person you wish to share this document with",
			article_share_from: "Article share from {0} for {1}",
			patent_share_from: "Patent share from {0} for {1}",
			supplementary_data_share_from: "Supplementary data share from {0} for {1}",
			clinical_trial_share_from: "Clinical trial share from {0} for {1}",
			phd_thesis_share_from: "PHD Thesis share from {0} for {1}",
			pinned_article: "Pinned article",
			mentions: "Mentions",
			recency: "Recency",
			send: "Send",
			cancel: "Cancel",
			next: "Next",
			techniques: "Techniques",
			genes: "Genes",
			applications: "Applications",
			products: "Products",
			product_techniques: "Product Techniques",
			journals: "Journals",
			authors: "Authors",
			dates: "Dates",
			reactivity: "Reactivity",
			dilution: "Dilution",
			institutions: "Institutions",
			research_area: "Research Area",
			research_areas: "Research Areas",
			detection_mode: "Detection Mode",
			covid_19: "COVID-19",
			covid_19_related: "COVID-19 related",
			industry: "Industry",
			industry_type: "Industry Type",
			cell_line: "Cell Line",
			sample_type: "Sample Type",
			search_for: "Search for {0}",
			reset: "Reset",
			filter_by: "Filter by ...",
			clear_filters: "Clear Filters",
			reset_filters: "Reset Filters",
			reset_all: "Reset All",
			no_results_found: "No Results Found...",
			has_not_been_referenced: "{0} has not yet been identified in any publications",
			company_highlight: "Company Highlight",
			total_things: "Total {0}",
			total_citations: "Total Citations",
			total_publications: "Total Publications",
			citations_last_year: "Citations Last Year",
			total_images: "Total Images",
			search_term: "Search term",
			enter_disease_name: "Enter disease name",
			enter_gene_assay_id: "Enter Gene or Assay ID",
			disease: "Disease",
			assay_gene: "Assay / Gene",
			your_search_returned: "Your search returned <span  id='bioz-w-results-count'>N/A</span> results (in <span id='bioz-w-results-time'>n/a</span> seconds)",
			your_search_returned_publications: "Your search found <span  id='bioz-w-results-count'>N/A</span> publication (in <span id='bioz-w-results-time'>n/a</span> seconds)",
			number_results_found: "<span  id='bioz-w-results-count-x'>N/A</span> results found",
			map: "Map",
			charts: "Charts",
			pro_badge_article_map: "Pro-Badge Articles Map",
			back_to_world_view: "Back to World View",
			featured_cover_images: "Featured Cover Images",
			from_most_prestigious: "From most prestigious scientific journals",
			currently_viewing: "Currently viewing",
			featured_publication: "Featured Publication",
			featured_publications: "Featured Publications",
			find_more_on_bioz: "Find More Citations On BIOZ",
			read_article_on_bioz: "Read Article on BIOZ",
			see_less_images: "See less images",
			see_more_images: "See more images",
			author_name_search: "Author Name Search",
			kit_vendors: "Kit Vendors",
			featured_articles: "Featured Articles",
			read_patent: "Read Patent",
			patent: "Patent",
			patents: "Patents",
			patent_share: "Share Patent",
			show_patents: "Show Patents",
			there_are_no_products: "There are no citations for this product currently.",
			suggested_filters: "Suggested Filters",
			peer_reviewed_only_publications: "Peer Reviewed Only Publications",
			supplementary: "Supplementary",
			supplementary_data: "Supplementary data",
			show_supplementary_data: "Show Supplementary Data",
			read_supplemental: "Read Document",
			supplemental_share: "Share Document",
			clinical_trial: "Clinical trial",
			clinical_trials: "Clinical trials",
			show_clinical_trials: "Show Clinical Trials",
			read_clinical_trial: "Read Document",
			clinical_trial_share: "Share Document",
			phd_thesis: "PhD Thesis",
			phd_theses: "PhD Theses",
			show_phd_theses: "Show PhD Theses",
			read_phd_thesis: "Read Document",
			phd_thesis_share: "Share Document",
			view_publication: "View Publication",
			search_in_title: "Search in title or text",
			type_anything_to_start: "Type anything to start searching",
			subject_filter: "{0} filter",
			from: "From",
			to: "To",
			this_product_was_sited: "This product was cited over {0} times, in {1} journal publications and in {3} article images, since {4}. The top journals (highest impact factor) it which this product was mentioned include {5}",
			the_top_applications: "The top applications/techniques that researchers performed with this product include {0} in the following top research areas {1}",
			the_bioz_signature_badge: "The Bioz Signature Badge is a one-of-a-kind, data-driven, objective and trusted per-product synopsis. These unique badges are based on real-world measured successful product usage, as documented by researchers in scientific publications. Patented Bioz AI technology analyzed more than 35 million published scientific articles, to identify these product data points.",
			cited_x_times: "Cited {0} times",
			cited_1_time: "Cited 1 time",
			article_citations: "Cited By Count",
			download_csv: "Download csv",
			product_citations_images: "Product Citations & Images",
			centrifuges: "Centrifuges",
			continents: "Continents",
			over: "Over",
			serving_all: "Serving",
			continents_with_life_changing: "Countries with Life Changing Research<br />Discoveries",
			trusted_by_more_than: "Trusted By More Than",
			scientists_around_the_world: "Scientists around the world",
			cns_papers: "CNS Papers",
			we_are_cited_in_top_journals: "We are Cited In Top Journals (partial)",
			impact_factor_greater_than: "Impact factor Greater > 10"
		},
		zh: {
			new: "新",
			more: "展开",
			less: "收回",
			product_page: "产品页面",
			landing_page: "登陆页面",
			view_product_page: "查看产品页面",
			view_product_citations: "查看产品引用",
			article_share: "文章分享",
			author_locations: "作者地点",
			read_article: "阅读文章",
			show: "每页结果",
			search: "搜索",
			search_all_publications: "搜索所有出版物",
			publication_filters: "出版物过滤器",
			citation: "引文",
			citations: "引用",
			product_citations: "产品引用",
			scientific_citations: "篇论文引用",
			citation_count: "引用次数",
			image: "图片",
			images: "图片",
			product_images: "产品图片",
			video: "视频",
			videos: "视频",
			table: "表格",
			tables: "表格",
			magnify_image: "放大图片",
			trend: "趋势",
			sort_by: "排序依据",
			date: "日期",
			export: "导出",
			export_page_citations: "导出本页全部引用",
			export_100_citations: "导出前 100 个引用",
			page_citations: "引文页数",
			first_100_citations: "前 100 次引用",
			article_snippet: "文章片段",
			figure: "图示",
			figure_legend: "图例",
			table_legend: "表格图例",
			video_legend: "视频图例",
			bioz_stars_product_rating: "Bioz Stars 产品评级",
			bioz_stars_description: "全球唯一的科研产品客观评级",
			learn_more: "了解更多",
			name: "名称",
			email:"电子邮件",
			share_this_article: "分享这篇文章",
			share_this_instructions: "请输入这篇文章将被分享到的人员姓名和电子邮件地址",
			share_this_patent: "分享此专利",
			share_this_patent_instructions: "请输入此专利将被分享到的人员姓名和电子邮件地址",
			share_this_supplemental: "分享此补充信息",
			share_this_supplemental_instructions: "请输入此补充信息将被分享到的人员姓名和电子邮件地址",
			share_this_clinical_trial: "分享此临床试验信息",
			share_this_clinical_trial_instructions: "请输入此临床试验信息被分享到的的人员姓名和电子邮件地址",
			share_this_phd_thesis: "分享此临床试验信息",
			share_this_phd_thesis_instructions: "请输入此临床试验信息被分享到的的人员姓名和电子邮件地址",
			article_share_from: "分享来自 {0} 的文章，内容为 {1}",
			patent_share_from: "{0} 为 {1} 提供的专利份额",
			supplementary_data_share_from: "来自 {0} 的 {1} 的补充数据共享",
			clinical_trial_share_from: "来自 {0} 的 {1} 临床试验份额",
			phd_thesis_share_from: "{0} 为 {1} 分享的博士学位论文",
			pinned_article: "文章已置顶",
			mentions: "提及频次",
			recency: "新近度",
			send: "发送",
			cancel: "取消",
			next: "下一个",
			techniques: "技术",
			genes: "基因",
			applications: "应用",
			products: "产品",
			product_techniques: "产品技术",
			journals: "期刊",
			authors: "作者",
			dates: "日期",
			reactivity: "反应活性",
			dilution: "稀释",
			institutions: "机构",
			research_area: "研究领域",
			research_areas: "研究领域",
			detection_mode: "检测方式",
			covid_19: "COVID-19",
			covid_19_related: "与新冠肺炎 (COVID-19) 相关",
			industry: "行业",
			industry_type: "行业类型",
			cell_line: "细胞系",
			sample_type: "样品类型",
			search_for: "搜索 {0}",
			reset: "重置",
			filter_by: "筛选依据",
			clear_filters: "清空筛选器",
			reset_filters: "重置筛选器",
			reset_all: "重置全部",
			no_results_found: "没有找到结果...",
			has_not_been_referenced: "尚未在任何出版物中引用 {0}",
			company_highlight: "公司亮点",
			total_things: "{0}的全部结果",
			total_citations: "总被引用次数",
			total_publications: "出版物总数",
			citations_last_year: "去年的全部引用次数",
			total_images: "全部图像",
			search_term: "搜索词",
			enter_disease_name: "输入疾病名称",
			enter_gene_assay_id: "输入基因或检测 ID",
			disease: "疾病",
			assay_gene: "检测/基因",
			your_search_returned: "您的搜索有 <span id='bioz-w-results-count'>N/A</span> 个结果（用时 <span id='bioz-w-results-time'>n/a</span > 秒）",
			your_search_returned_publications: "您的搜索有 <span id='bioz-w-results-count'>N/A</span> 出版物结果（用时 <span id='bioz-w-results-time'>n/a</span>秒）",
			number_results_found: "找到 <span  id='bioz-w-results-count-x'>N/A</span> 个结果",
			map: "总览图",
			charts: "图表",
			pro_badge_article_map: "Pro-Badge 文章总览图",
			back_to_world_view: "回到世界视图",
			featured_cover_images: "精选封面图片",
			from_most_prestigious: "来自最负盛名的科学期刊",
			currently_viewing: "当前正在查看",
			featured_publication: "精选出版物",
			featured_publications: "精选出版物",
			find_more_on_bioz: "在 BIOZ 上查找更多引文",
			read_article_on_bioz: "在 BIOZ 上阅读文章",
			see_less_images: "展示更少图片",
			see_more_images: "查看更多图片",
			author_name_search: "按作者姓名搜索",
			kit_vendors: "试剂盒供应商",
			featured_articles: "精选文章",
			read_patent: "阅读专利",
			patent: "专利",
			patents: "专利",
			patent_share: "分享专利",
			show_patents: "显示专利",
			there_are_no_products: "目前没有对该产品的引用。",
			suggested_filters: "推荐的筛选器",
			peer_reviewed_only_publications: "仅经过同行评审的出版物",
			supplementary: "补充",
			supplementary_data: "补充数据",
			show_supplementary_data: "显示补充数据",
			read_supplemental: "阅读补充信息",
			supplemental_share: "共享补充信息",
			clinical_trial: "临床试验信息",
			clinical_trials: "临床试验信息",
			show_clinical_trials: "显示临床试验信息",
			read_clinical_trial: "阅读临床试验信息",
			clinical_trial_share: "共享文档",
			phd_thesis: "博士论文",
			phd_theses: "博士论文",
			show_phd_theses: "显示博士论文",
			read_phd_thesis: "阅读文档",
			phd_thesis_share: "共享文档",
			view_publication: "查看出版物",
			search_in_title: "在标题或文本中搜索",
			type_anything_to_start: "输入任何内容开始搜索",
			subject_filter: "{0}筛选器",
			from: "从",
			to: "到",
			this_product_was_sited: "自 {4} 起，该产品在 {1} 篇期刊出版物和 {3} 个文章图片中被引用超过 {0} 次。提及该产品的、影响因子最高的顶级期刊包括 {5}",
			the_top_applications: "研究人员应用此产品进行的、最广泛的顶级应用场景或技术，包括以下顶级研究领域的 {0} {1}",
			the_bioz_signature_badge: "Bioz 签名徽章是一种针对每个产品的、独一无二的、数据驱动的、客观且值得信赖的概要。基于研究人员在科学出版物中记录的数据，这些独特的徽章反映了现实世界中检验成功的产品的使用情况。为了分析这些产品数据，具有独家专利的 Bioz AI 技术已经分析了超过 3500 万篇已发表的科学文章，。",
			cited_x_times: "被引用 {0} 次",
			cited_1_time: "被引用 1 次",
			article_citations: "文章引用",
			download_csv: "下载文件",
			product_citations_images: "产品引用和图片",
			centrifuges: "离心机",
			continents: "大洲科学家认可",
			over: "结束",
			serving_all: "服务",
			continents_with_life_changing: "有改变生活的研究发现的国家",
			trusted_by_more_than: "受到超过信任",
			scientists_around_the_world: "世界各地的科学家",
			cns_papers: "篇 CNS 论文",
			we_are_cited_in_top_journals: "我们被顶级期刊引用（部分）",
			impact_factor_greater_than: "影响因子大于 10"
		}
	};

	this.locale = "en";
	var _locales_array = ["en", "zh"];
	if (typeof(_locale) != 'undefined' && _locales_array.indexOf(_locale) != -1 ) {
		this.locale = _locale;
	}

	this.i18l = function(key, value_1, value_2) {
		if (!value_1) {
			return this.locale_dict[this.locale][key];
		} else {
			var return_str = this.locale_dict[this.locale][key];
			return_str = return_str.replace("{0}", value_1);
			if (value_2) {
				return_str = return_str.replace("{1}", value_2);
			}
			return return_str;
		}
	}
}

export {v_widget_lang};